name: shopspot
description: 'Your personal shopping companion. Find nearby stores, explore details, track distances, and curate your favorite shopping destinations all in one place.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.4.0
  fluttertoast: ^8.2.12
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.3.0
  flutter_map:
  latlong2: 
  image_picker: ^1.1.2
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.2
  geolocator: ^11.0.0
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.2
  flutter_native_splash: ^2.4.6
  url_launcher: ^6.3.1
  shimmer: ^3.0.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator:
  build_runner:
flutter:
  uses-material-design: true
  assets:
    - assets/SplashBrand.png
    - assets/SplashLogo.png
    - assets/AppLogo.png
